### ISSUE TITLE
An unhandled exception of type 'System.AccessViolationException' occurred in Grib.Api.dll” randomly

### ISSUE THREAD

**Issue by VishmayShah** [0x1mason/GribApi.NET#14] opened 2015-10-30 05:30 UTC
Hello,

We are facing issue on grib api. That is throwing Execption of type “An unhandled exception of type 'System.AccessViolationException' occurred in Grib.Api.dll” randomly version="0.5.1" 

As we are sure that we have completely/properly installed gribapi, mostly first time data is also decoded and we are able to read and save also.
After that after some random steps we are facing this issue in following cases .
1.  When in my winservice project I have called 
using (gribFile = new GribFile(readPath))
from  void Main() method for 1 time only , after downloading file, saving data, deleting file, when using brackets are closed  and main() is also closed then this error occurs
2.  When I call gribfile repeatively, I receive this error on second or third file, I have cleared all variables and extra spaces, and yes in second or third file the error occurs anywhere at any event like dbinsert or delete data the save grib api exeption is thrown
3.  It is also not able handled in try catch so program break downs.

Please resolve this issue, it stuck my program

Thank you for your attantion

**Comment by 0x1mason** [comment] 2015-10-30 14:27
Sorry to hear you're having problems. I will see if I can reproduce these problems.

I resolved some access violations in v0.6.0, which I published a couple days ago. Please try the new version while I work on this. Please also let me know if it makes any difference if the debugger is attached (eg, if you double click on the exe, do you still get the exceptions).

Thanks!

**Comment by 0x1mason** [comment] 2015-11-01 21:01
@VishmayShah 
Are you deleting the file _inside_ the `using` statement? That's a really bad idea. That should be easily correctable in your code.
1. I couldn't replicate an access violation in the scenarios you mentioned. There was an exception when closing file handles that might be part of the issues you experienced. I just pushed a fix (v0.6.1) that may solve your problems.
2. What is the message in the GribApiException you mention?
3. You cannot catch access violations. Even if you could, you should consider them fatal and close immediately.

Please install v0.6.1 and tell me if that resolves your issue. If it doesn't, then I'll need examples of the code that is causing you problems.

**Comment by VishmayShah** [comment] 2015-11-01 22:23
hello @mason,
First of all thank you for quick reply,
and Sorry for my Late response as weekends

the message is same as above An unhandled exception of type 'System.AccessViolationException' occurred in Grib.Api.dll” randomly version="0.5.1"

while we faced this issue we have used our grib files more than 6 mb containing 1050000 records each and there were near about 13 files for decode but not all of them was called. only 2nd or 3rd file thrown that exception

in previous Friday we have upgraded code to  6.0 and still getting error for multiple files. although we haven't check for an exception when closing file handles but will check on today. 

i cannot upload grib files on git hub and cannot share link to download as it contains confidential details for company. so i will give you my email id. if you can give your email id directly on my mail, i will send you that files directly. so i have to go to company for that that is after 4:30 hours. emailid is there in the company. so sorry for the inconviniance

**Comment by 0x1mason** [comment] 2015-11-02 01:13
Thanks for the extra information.  My email is etmillin@gmail.com if you'd like to contact me directly. I'm also willing to sign non-disclosure agreement, provide references, etc., as needed.

Let me know how it goes with v0.6.1. Obviously I need to automate the assembly versioning changes because I've forgotten to increment along with the package number.

**Comment by 0x1mason** [comment] 2015-11-02 15:25
@VishmayShah 

Thanks for the files.

I still cannot replicate the issue. First, here are the settings I tried:
- Debug and Release
- Any CPU, x64, and x86
- v0.6.1
- Console application

My machine:
- Win 10 x64
- 16GB RAM (though even on x64, I never saw more than 50MB of RAM used)

Code:

``` csharp
using Grib.Api;
using System;

namespace VComponentTest
{
    class Program
    {
        static void Main (string[] args)
        {
            // worked with and without this loop
            // for (int i = 0; i < 10; i++ )
            {
                Decode1();
                Decode2();
            }
        }

        static void Decode1 ()
        {
            using (var file = new GribFile("File1.grb2"))
            {
                foreach (var msg in file)
                {
                    foreach (var val in msg.GeoSpatialValues)
                    {
                        Console.WriteLine("Lat: {0} Lon: {1} Val: {2}", val.Latitude, val.Longitude, val.Value);
                    }
                }
            } 
        }

        static void Decode2 ()
        {
            using (var file = new GribFile("File2.grb2"))
            {
                foreach (var msg in file)
                {
                    foreach (var val in msg.GeoSpatialValues)
                    {
                        Console.WriteLine("Lat: {0} Lon: {1} Val: {2}", val.Latitude, val.Longitude, val.Value);
                    }
                }
            }
        }
    }
}

```

Possible next steps:
1. Send me your project or tell me what you're doing that's significantly different.
2. See if you can get my code or similar working.
3. If my code works, try gradually reintroducing your code until it breaks. Let me know what triggers the breakage.

**Comment by VishmayShah** [comment] 2015-11-03 07:45
Thanks to your support, i was able to resolve the problem.
the problem was that i was having two project
1. class library and 
2. Windows app that referance to 1. class library
both of them were referencing grib api, so i remove reference from 2. Windows app and moved coding to 1. class library
and the problem was solved
thank you

**Comment by 0x1mason** [comment] 2015-11-03 15:09
Great! Glad you got it resolved.

**Closed as completed** 2015-11-03 16:27 UTC
Labels: bug

**Comment by VishmayShah** [comment] 2015-11-16 08:48
Restarted error without reason
An unhandled exception of type 'System.AccessViolationException' occurred in Grib.Api.dll

Additional information: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

this time i have arranged stack trace, can you give me reason for this. i am not finding any defect in my code
   at Grib.Api.Interop.Util.GribApiNative.DestroyFileHandleProxy(IntPtr fileHandleProxy)
   at Grib.Api.GribFile.OnDispose(Boolean disposing) in c:\Users\eric\GribApi.NET\src\GribApi.NET\Grib.Api\GribFile.cs:line 90
   at Grib.Api.Interop.AutoRef.Dispose(Boolean disposing) in c:\Users\eric\GribApi.NET\src\GribApi.NET\Grib.Api\Interop\AutoRef.cs:line 63
   at Grib.Api.Interop.AutoRef.Finalize() in c:\Users\eric\GribApi.NET\src\GribApi.NET\Grib.Api\Interop\AutoRef.cs:line 51

**Comment by 0x1mason** [comment] 2015-11-16 13:48
This is the error related to closing file handles that I mentioned. Please
install the latest version 0.6.3, and let me know if the problem persists.

**Comment by 0x1mason** [comment] 2015-11-16 14:10
If this is still occurring, please let me know when it occurs. Thank you.

**Comment by VishmayShah** [comment] 2015-11-24 03:32
i made 2 thing
1. i redownloaded grib api and 2.installed latest version
which solution did the trick, i don't know but it has been started working properly
thank you

**Comment by 0x1mason** [comment] 2015-11-24 17:36
Great to hear!

Should have some more fixes published soon.

**Comment by VishmayShah** [comment] 2015-11-25 10:48
where is 0.6.3 in packagemanager console i recently used "Install-Package Grib.Api -pre" and latest version was 0.6.1

**Comment by 0x1mason** [comment] 2015-11-25 16:12
I meant to type 0.6.2 before, but now 0.6.3 is available: https://www.nuget.org/packages/Grib.Api

**Comment by VishmayShah** [comment] 2015-12-01 03:06
Hello,
beta version command
"-pre" was containing 0.6.1
while main version was 0.6.3
beta have more higher version than stable so just asked

On Wed, Nov 25, 2015 at 9:42 PM, Eric Millin notifications@github.com
wrote:

> I meant to type 0.6.2 before, but now 0.6.3 is available:
> https://www.nuget.org/packages/Grib.Api
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/0x1mason/GribApi.NET/issues/14#issuecomment-159657852
> .

## 

Vishmay Shah
9427376960
